f1 = input("Enter first fruit: ")
f2 = input("Enter second fruit: ")
f3 = input("Enter third fruit: ")
f4 = input("Enter fourth fruit: ")
f5 = input("Enter fifth fruit: ")
f6 = input("Enter sixth fruit: ")
f7 = input("Enter seventh fruit: ")

myFruitList = (f1, f2, f3, f4, f5, f6, f7)
print(myFruitList)
